bcfg2-selinux.spec: Fail silently when missing prerequisites
Previously, we were failing hard if build dependencies were not met.

/bin/sed: can't read /usr/share/selinux/devel/policyhelp: No such file or directory

This commit allows rpmbuild to fall through so that we can see the real
problem.

error: Failed build dependencies:
	/usr/share/selinux/devel/policyhelp is needed by bcfg2-selinux-1.3.1-1.noarch

Signed-off-by: Sol Jerome <sol.jerome@gmail.com>