Plugins/Cfg: fix entry attributes
lxml requires that all attributes are strings, so first convert them.
This fixes this traceback:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Core.py", line 586, in BindStructures
    self.BindStructure(astruct, metadata)
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Statistics.py", line 120, in inner
    return func(obj, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Core.py", line 608, in BindStructure
    self.Bind(entry, metadata)
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Core.py", line 654, in Bind
    metadata)
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Plugins/Cfg/__init__.py", line 626, in bind_entry
    self.bind_info_to_entry(entry, metadata)
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Plugins/Cfg/__init__.py", line 711, in bind_info_to_entry
    CfgDefaultInfo().bind_info_to_entry(entry, metadata)
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Plugins/Cfg/__init__.py", line 512, in bind_info_to_entry
    entry.attrib[key] = value
  File "lxml.etree.pyx", line 2159, in lxml.etree._Attrib.__setitem__ (src/lxml/lxml.etree.c:48491)
  File "apihelpers.pxi", line 563, in lxml.etree._setAttributeValue (src/lxml/lxml.etree.c:15471)
  File "apihelpers.pxi", line 1364, in lxml.etree._utf8 (src/lxml/lxml.etree.c:22039)
TypeError: Argument must be bytes or unicode, got 'bool'