testsuite: boto requires google_compute_engine
At least with pythn2.6 boto requires google_compute_engine:

> Traceback (most recent call last):
>   File ".../site-packages/boto/__init__.py", line 1216, in <module>
>     boto.plugin.load_plugins(config)
>   File ".../site-packages/boto/plugin.py", line 93, in load_plugins
>     _import_module(file)
>   File ".../site-packages/boto/plugin.py", line 75, in _import_module
>     return imp.load_module(name, file, filename, data)
>   File ".../dist-packages/google_compute_engine/boto/compute_auth.py", line 19, in <module>
>     from google_compute_engine import logger
> ImportError: No module named google_compute_engine