Fix bcfg2-reports --badentry and --extraentry
The reporting system schema has been changed.  This change lead to
exceptions such as

| AttributeError: 'Entries_interactions' object has no attribute 'name'

when running bcfg2-reports with the --badentry or --extraentry options.