EncapPackages: How's this for fun: If you have 2 seperate python binaries at different locations, both named "python", then somehow they both pick up the same python shared libraries, but if you call the second one using a different name, you get the shared library it's supposed to be using. This hit me when I installed a non-bcfg2 python in /usr/local, and suddenly bcfg2 stopped working with:
Traceback (most recent call last):
  File "/usr/local/bin/bcfg2", line 14, in ?
    import Bcfg2.Options
ImportError: No module named Bcfg2.Options

Because it was using the python that thought modules were under /usr/local/lib instead of /usr/local/lib/bcfg2/lib

This patch should fix it.

git-svn-id: https://svn.mcs.anl.gov/repos/bcfg/trunk/bcfg2@3511 ce84e21b-d406-0410-9b95-82705330c041