Client/Proxy.py: Provide more useful error message
Previously, having a ca specified in the client bcfg2.conf which pointed
to a file that didn't exist resulted in the following:

    Unknown failure: [Errno 2] No such file or directory (IOError)
    Unknown failure: [Errno 2] No such file or directory (IOError)
    Unknown failure: [Errno 2] No such file or directory (IOError)
    Fatal error: Failed to declare version: Unknown failure: [Errno 2] No such file or directory (IOError)

This commit provides more information about the actual cause of the
issue.

Signed-off-by: Sol Jerome <sol.jerome@gmail.com>